### ISSUE TITLE
Create relation with Redis charm

### ISSUE THREAD

**Issue by sebas5384** [sebas5384/charm-drupal#17]
Relations to be set:

``` yaml
requires:
  cache-redis:
    interface: redis-master
  cache-memcached:
    interface: memcache
```
